import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {}

const categoryList = {
  categories: [
    {
      idCategory: '1',
      strCategory: 'Beef',
      strCategoryThumb: 'https://www.themealdb.com/images/category/beef.png',
      strCategoryDescription:
        'Beef is the culinary name for meat from cattle, particularly skeletal muscle. Humans have been eating beef since prehistoric times.[1] Beef is a source of high-quality protein and essential nutrients.[2]',
    },
    {
      idCategory: '2',
      strCategory: 'Chicken',
      strCategoryThumb: 'https://www.themealdb.com/images/category/chicken.png',
      strCategoryDescription:
        'Chicken is a type of domesticated fowl, a subspecies of the red junglefowl. It is one of the most common and widespread domestic animals, with a total population of more than 19 billion as of 2011.[1] Humans commonly keep chickens as a source of food (consuming both their meat and eggs) and, more rarely, as pets.',
    },
    {
      idCategory: '3',
      strCategory: 'Dessert',
      strCategoryThumb: 'https://www.themealdb.com/images/category/dessert.png',
      strCategoryDescription:
        'Dessert is a course that concludes a meal. The course usually consists of sweet foods, such as confections dishes or fruit, and possibly a beverage such as dessert wine or liqueur, however in the United States it may include coffee, cheeses, nuts, or other savory items regarded as a separate course elsewhere. In some parts of the world, such as much of central and western Africa, and most parts of China, there is no tradition of a dessert course to conclude a meal.\r\n\r\nThe term dessert can apply to many confections, such as biscuits, cakes, cookies, custards, gelatins, ice creams, pastries, pies, puddings, and sweet soups, and tarts. Fruit is also commonly found in dessert courses because of its naturally occurring sweetness. Some cultures sweeten foods that are more commonly savory to create desserts.',
    },
  ],
};

const mealList = {
  meals: [
    {
      idMeal: '52874',
      strMeal: 'Beef and Mustard Pie',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'British',
      strInstructions:
        "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg',
      strTags: 'Meat,Pie',
      strYoutube: 'https://www.youtube.com/watch?v=nMyBC9staMU',
      strIngredient1: 'Beef',
      strIngredient2: 'Plain Flour',
      strIngredient3: 'Rapeseed Oil',
      strIngredient4: 'Red Wine',
      strIngredient5: 'Beef Stock',
      strIngredient6: 'Onion',
      strIngredient7: 'Carrots',
      strIngredient8: 'Thyme',
      strIngredient9: 'Mustard',
      strIngredient10: 'Egg Yolks',
      strIngredient11: 'Puff Pastry',
      strIngredient12: 'Green Beans',
      strIngredient13: 'Butter',
      strIngredient14: 'Salt',
      strIngredient15: 'Pepper',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1kg',
      strMeasure2: '2 tbs',
      strMeasure3: '2 tbs',
      strMeasure4: '200ml',
      strMeasure5: '400ml',
      strMeasure6: '1 finely sliced',
      strMeasure7: '2 chopped',
      strMeasure8: '3 sprigs',
      strMeasure9: '2 tbs',
      strMeasure10: '2 free-range',
      strMeasure11: '400g',
      strMeasure12: '300g',
      strMeasure13: '25g',
      strMeasure14: 'pinch',
      strMeasure15: 'pinch',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52878',
      strMeal: 'Beef and Oyster pie',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'British',
      strInstructions:
        'Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg',
      strTags: 'Pie',
      strYoutube: 'https://www.youtube.com/watch?v=ONX74yP6JnI',
      strIngredient1: 'Beef',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Shallots',
      strIngredient4: 'Garlic',
      strIngredient5: 'Bacon',
      strIngredient6: 'Thyme',
      strIngredient7: 'Bay Leaf',
      strIngredient8: 'Stout',
      strIngredient9: 'Beef Stock',
      strIngredient10: 'Corn Flour',
      strIngredient11: 'Oysters',
      strIngredient12: 'Plain Flour',
      strIngredient13: 'Salt',
      strIngredient14: 'Butter',
      strIngredient15: 'Eggs',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '900g',
      strMeasure2: '3 tbs',
      strMeasure3: '3',
      strMeasure4: '2 cloves minced',
      strMeasure5: '125g',
      strMeasure6: '1 tbs chopped',
      strMeasure7: '2',
      strMeasure8: '330ml',
      strMeasure9: '400ml',
      strMeasure10: '2 tbs',
      strMeasure11: '8',
      strMeasure12: '400g',
      strMeasure13: 'pinch',
      strMeasure14: '250g',
      strMeasure15: 'To Glaze',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53071',
      strMeal: 'Beef Asado',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'Filipino',
      strInstructions:
        '0.\tCombine beef, crushed peppercorn, soy sauce, vinegar, dried bay leaves, lemon, and tomato sauce. Mix well. Marinate beef for at least 30 minutes.\r\n1.\tPut the marinated beef in a cooking pot along with remaining marinade. Add water. Let boil.\r\n2.\tAdd Knorr Beef Cube. Stir. Cover the pot and cook for 40 minutes in low heat.\r\n3.\tTurn the beef over. Add tomato paste. Continue cooking until beef tenderizes. Set aside.\r\n4.\tHeat oil in a pan. Fry the potato until it browns. Turn over and continue frying the opposite side. Remove from the pan and place on a clean plate. Do the same with the carrots.\r\n5.\tSave 3 tablespoons of cooking oil from the pan where the potato was fried. Saute onion and garlic until onion softens.\r\n6.\tPour-in the sauce from the beef stew. Let boil. Add the beef. Cook for 2 minutes.\r\n7.\tAdd butter and let it melt. Continue cooking until the sauce reduces to half.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=lNlK8DVhXXA',
      strIngredient1: 'Beef',
      strIngredient2: 'Beef Stock Concentrate',
      strIngredient3: 'Tomato Puree',
      strIngredient4: 'Water',
      strIngredient5: 'Soy Sauce',
      strIngredient6: 'White Wine Vinegar',
      strIngredient7: 'Pepper',
      strIngredient8: 'Bay Leaf',
      strIngredient9: 'Lemon',
      strIngredient10: 'Tomato Sauce',
      strIngredient11: 'Butter',
      strIngredient12: 'Olive Oil',
      strIngredient13: 'Onion',
      strIngredient14: 'Garlic',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1.5kg',
      strMeasure2: '1',
      strMeasure3: '8 ounces',
      strMeasure4: '3 cups ',
      strMeasure5: '6 tablespoons',
      strMeasure6: '1 tbs',
      strMeasure7: '2 tbs',
      strMeasure8: '4',
      strMeasure9: '1/2 ',
      strMeasure10: '2 tbs',
      strMeasure11: '3 tbs',
      strMeasure12: '1/2 cup ',
      strMeasure13: '1 chopped',
      strMeasure14: '4 cloves',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://panlasangpinoy.com/beef-asado/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53050',
      strMeal: 'Ayam Percik',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Malaysian',
      strInstructions:
        "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/020z181619788503.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=9ytR28QK6I8',
      strIngredient1: 'Chicken Thighs',
      strIngredient2: 'Challots',
      strIngredient3: 'Ginger',
      strIngredient4: 'Garlic Clove',
      strIngredient5: 'Cayenne Pepper',
      strIngredient6: 'Turmeric',
      strIngredient7: 'Cumin',
      strIngredient8: 'Coriander',
      strIngredient9: 'Fennel',
      strIngredient10: 'Tamarind Paste',
      strIngredient11: 'Coconut Milk',
      strIngredient12: 'Sugar',
      strIngredient13: 'Water',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '6',
      strMeasure2: '16',
      strMeasure3: '1 1/2 ',
      strMeasure4: '6',
      strMeasure5: '8',
      strMeasure6: '2 tbs',
      strMeasure7: '1 1/2 ',
      strMeasure8: '1 1/2 ',
      strMeasure9: '1 1/2 ',
      strMeasure10: '2 tbs',
      strMeasure11: '1 can ',
      strMeasure12: '1 tsp ',
      strMeasure13: '1 cup ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource:
        'http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52940',
      strMeal: 'Brown Stew Chicken',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Jamaican',
      strInstructions:
        'Squeeze lime over chicken and rub well. Drain off excess lime juice.\r\nCombine tomato, scallion, onion, garlic, pepper, thyme, pimento and soy sauce in a large bowl with the chicken pieces. Cover and marinate at least one hour.\r\nHeat oil in a dutch pot or large saucepan. Shake off the seasonings as you remove each piece of chicken from the marinade. Reserve the marinade for sauce.\r\nLightly brown the chicken a few pieces at a time in very hot oil. Place browned chicken pieces on a plate to rest while you brown the remaining pieces.\r\nDrain off excess oil and return the chicken to the pan. Pour the marinade over the chicken and add the carrots. Stir and cook over medium heat for 10 minutes.\r\nMix flour and coconut milk and add to stew, stirring constantly. Turn heat down to minimum and cook another 20 minutes or until tender.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg',
      strTags: 'Stew',
      strYoutube: 'https://www.youtube.com/watch?v=_gFB1fkNhXs',
      strIngredient1: 'Chicken',
      strIngredient2: 'Tomato',
      strIngredient3: 'Onions',
      strIngredient4: 'Garlic Clove',
      strIngredient5: 'Red Pepper',
      strIngredient6: 'Carrots',
      strIngredient7: 'Lime',
      strIngredient8: 'Thyme',
      strIngredient9: 'Allspice',
      strIngredient10: 'Soy Sauce',
      strIngredient11: 'Cornstarch',
      strIngredient12: 'Coconut Milk',
      strIngredient13: 'Vegetable Oil',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 whole',
      strMeasure2: '1 chopped',
      strMeasure3: '2 chopped',
      strMeasure4: '2 chopped',
      strMeasure5: '1 chopped',
      strMeasure6: '1 chopped',
      strMeasure7: '1',
      strMeasure8: '2 tsp',
      strMeasure9: '1 tsp ',
      strMeasure10: '2 tbs',
      strMeasure11: '2 tsp',
      strMeasure12: '2 cups ',
      strMeasure13: '1 tbs',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'http://www.geniuskitchen.com/recipe/authentic-jamaican-brown-stew-chicken-347996',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52850',
      strMeal: 'Chicken Couscous',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Moroccan',
      strInstructions:
        'Heat the olive oil in a large frying pan and cook the onion for 1-2 mins just until softened. Add the chicken and fry for 7-10 mins until cooked through and the onions have turned golden. Grate over the ginger, stir through the harissa to coat everything and cook for 1 min more.\r\n\r\nTip in the apricots, chickpeas and couscous, then pour over the stock and stir once. Cover with a lid or tightly cover the pan with foil and leave for about 5 mins until the couscous has soaked up all the stock and is soft. Fluff up the couscous with a fork and scatter over the coriander to serve. Serve with extra harissa, if you like.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=GZQGy9oscVk',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Onion',
      strIngredient3: 'Chicken Breast',
      strIngredient4: 'Ginger',
      strIngredient5: 'Harissa Spice',
      strIngredient6: 'Dried Apricots',
      strIngredient7: 'Chickpeas',
      strIngredient8: 'Couscous',
      strIngredient9: 'Chicken Stock',
      strIngredient10: 'Coriander',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 tbsp',
      strMeasure2: '1 chopped',
      strMeasure3: '200g',
      strMeasure4: 'pinch',
      strMeasure5: '2 tblsp ',
      strMeasure6: '10',
      strMeasure7: '220g',
      strMeasure8: '200g',
      strMeasure9: '200ml',
      strMeasure10: 'Handful',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'https://www.bbcgoodfood.com/recipes/13139/onepan-chicken-couscous',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52768',
      strMeal: 'Apple Frangipan Tart',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions:
        'Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
      strTags: 'Tart,Baking,Fruity',
      strYoutube: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
      strIngredient1: 'digestive biscuits',
      strIngredient2: 'butter',
      strIngredient3: 'Bramley apples',
      strIngredient4: 'butter, softened',
      strIngredient5: 'caster sugar',
      strIngredient6: 'free-range eggs, beaten',
      strIngredient7: 'ground almonds',
      strIngredient8: 'almond extract',
      strIngredient9: 'flaked almonds',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '175g/6oz',
      strMeasure2: '75g/3oz',
      strMeasure3: '200g/7oz',
      strMeasure4: '75g/3oz',
      strMeasure5: '75g/3oz',
      strMeasure6: '2',
      strMeasure7: '75g/3oz',
      strMeasure8: '1 tsp',
      strMeasure9: '50g/1¾oz',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52894',
      strMeal: 'Battenberg Cake',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions:
        'Heat oven to 180C/160C fan/gas 4 and line the base and sides of a 20cm square tin with baking parchment (the easiest way is to cross 2 x 20cm-long strips over the base). To make the almond sponge, put the butter, sugar, flour, ground almonds, baking powder, eggs, vanilla and almond extract in a large bowl. Beat with an electric whisk until the mix comes together smoothly. Scrape into the tin, spreading to the corners, and bake for 25-30 mins – when you poke in a skewer, it should come out clean. Cool in the tin for 10 mins, then transfer to a wire rack to finish cooling while you make the second sponge.\r\nFor the pink sponge, line the tin as above. Mix all the ingredients together as above, but don’t add the almond extract. Fold in some pink food colouring. Then scrape it all into the tin and bake as before. Cool.\r\nTo assemble, heat the jam in a small pan until runny, then sieve. Barely trim two opposite edges from the almond sponge, then well trim a third edge. Roughly measure the height of the sponge, then cutting from the well-trimmed edge, use a ruler to help you cut 4 slices each the same width as the sponge height. Discard or nibble leftover sponge. Repeat with pink cake.\r\nTake 2 x almond slices and 2 x pink slices and trim so they are all the same length. Roll out one marzipan block on a surface lightly dusted with icing sugar to just over 20cm wide, then keep rolling lengthways until the marzipan is roughly 0.5cm thick. Brush with apricot jam, then lay a pink and an almond slice side by side at one end of the marzipan, brushing jam in between to stick sponges, and leaving 4cm clear marzipan at the end. Brush more jam on top of the sponges, then sandwich remaining 2 slices on top, alternating colours to give a checkerboard effect. Trim the marzipan to the length of the cakes.\r\nCarefully lift up the marzipan and smooth over the cake with your hands, but leave a small marzipan fold along the bottom edge before you stick it to the first side. Trim opposite side to match size of fold, then crimp edges using fingers and thumb (or, more simply, press with prongs of fork). If you like, mark the 10 slices using the prongs of a fork.\r\nAssemble second Battenberg and keep in an airtight box or well wrapped in cling film for up to 3 days. Can be frozen for up to a month.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/ywwrsp1511720277.jpg',
      strTags: 'Cake,Sweet',
      strYoutube: 'https://www.youtube.com/watch?v=aB41Q7kDZQ0',
      strIngredient1: 'Butter',
      strIngredient2: 'Caster Sugar',
      strIngredient3: 'Self-raising Flour',
      strIngredient4: 'Almonds',
      strIngredient5: 'Baking Powder',
      strIngredient6: 'Eggs',
      strIngredient7: 'Vanilla Extract',
      strIngredient8: 'Almond Extract',
      strIngredient9: 'Butter',
      strIngredient10: 'Caster Sugar',
      strIngredient11: 'Self-raising Flour',
      strIngredient12: 'Almonds',
      strIngredient13: 'Baking Powder',
      strIngredient14: 'Eggs',
      strIngredient15: 'Vanilla Extract',
      strIngredient16: 'Almond Extract',
      strIngredient17: 'Pink Food Colouring',
      strIngredient18: 'Apricot',
      strIngredient19: 'Marzipan',
      strIngredient20: 'Icing Sugar',
      strMeasure1: '175g',
      strMeasure2: '175g',
      strMeasure3: '140g',
      strMeasure4: '50g',
      strMeasure5: '½ tsp',
      strMeasure6: '3 Medium',
      strMeasure7: '½ tsp',
      strMeasure8: '¼ teaspoon',
      strMeasure9: '175g',
      strMeasure10: '175g',
      strMeasure11: '140g',
      strMeasure12: '50g',
      strMeasure13: '½ tsp',
      strMeasure14: '3 Medium',
      strMeasure15: '½ tsp',
      strMeasure16: '¼ teaspoon',
      strMeasure17: '½ tsp',
      strMeasure18: '200g',
      strMeasure19: '1kg',
      strMeasure20: 'Dusting',
      strSource: 'https://www.bbcgoodfood.com/recipes/1120657/battenberg-cake',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52961',
      strMeal: 'Budino Di Ricotta',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Italian',
      strInstructions:
        'Mash the ricotta and beat well with the egg yolks, stir in the flour, sugar, cinnamon, grated lemon rind and the rum and mix well. You can do this in a food processor. Beat the egg whites until stiff, fold in and pour into a buttered and floured 25cm cake tin. Bake in the oven at 180ºC/160ºC fan/gas 4 for about 40 minutes, or until it is firm.\r\n\r\nServe hot or cold dusted with icing sugar.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1549542877.jpg',
      strTags: 'Cake,Baking,Desert,Sweet,Alcoholic,Calorific',
      strYoutube: 'https://www.youtube.com/watch?v=6dzd6Ra6sb4',
      strIngredient1: 'Ricotta',
      strIngredient2: 'Eggs',
      strIngredient3: 'Flour',
      strIngredient4: 'Sugar',
      strIngredient5: 'Cinnamon',
      strIngredient6: 'Lemons',
      strIngredient7: 'Dark Rum',
      strIngredient8: 'Icing Sugar',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '500g',
      strMeasure2: '4 large',
      strMeasure3: '3 tbs',
      strMeasure4: '250g',
      strMeasure5: '1 tsp ',
      strMeasure6: 'Grated Zest of 2',
      strMeasure7: '5 tbs',
      strMeasure8: 'sprinking',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'https://thehappyfoodie.co.uk/recipes/ricotta-cake-budino-di-ricotta',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
